M48
; DRILL file {KiCad 9.0.4} date 2026-07-25T18:59:20+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-25T18:59:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.400
%
G90
G05
T1
X34.19Y-90.5
X34.19Y-137.5
X45.59Y-90.5
X45.59Y-137.5
T2
X32.1Y-78.0
M30
